INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small package', 'Only the most necessary with a mix of colours', '/img/subscriptions/newborn_small_1.jpg', '/img/subscriptions/newborn_small_2.jpg', '/img/subscriptions/newborn_small_3.jpg', '/img/subscriptions/newborn_small_4.jpg', 'NEWBORN', 'standard', 200);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small - Rocky package', 'For the inner rockstar', '/img/subscriptions/rockstar_newborn01.jpg', '/img/subscriptions/rockstar_newborn02.jpg', '/img/subscriptions/rockstar_newborn03.jpg', '/img/subscriptions/rockstar_newborn04.jpg', 'NEWBORN', 'Rocky', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small - Conscious package', 'Clothes from our conscious collections', '/img/subscriptions/conscious_newborn01.jpg', '/img/subscriptions/conscious_newborn02.jpg', '/img/subscriptions/conscious_newborn03.jpg', '/img/subscriptions/conscious_newborn04.jpg', 'NEWBORN', 'Conscious', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete package', 'Everything that your child will need with a mix of colours', '/img/subscriptions/baby_complete_3.jpg','/img/subscriptions/colorful_newborn.jpg','/img/subscriptions/colorful_newborn01.jpg','/img/subscriptions/colorful_newborn02.jpg', 'NEWBORN', 'standard', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete - Rocky package', 'For the inner rockstar', '/img/subscriptions/rockstar_newborn04.jpg', '/img/subscriptions/rockstar_newborn02.jpg', '/img/subscriptions/rockstar_newborn03.jpg', '/img/subscriptions/rockstar_newborn01.jpg', 'NEWBORN', 'Rocky', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete - Conscious package', 'Clothes from our conscious collections', '/img/subscriptions/conscious_newborn04.jpg', '/img/subscriptions/conscious_newborn02.jpg', '/img/subscriptions/conscious_newborn03.jpg', '/img/subscriptions/conscious_newborn01.jpg', 'NEWBORN', 'Conscious', 300);

INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small package', 'Only the most necessary with a mix of colours', '/img/subscriptions/baby_complete_1.jpg','/img/subscriptions/baby_complete_2.jpg','/img/subscriptions/baby_complete_3.jpg','/img/subscriptions/baby_complete_4.jpg', 'BABY', 'standard', 200);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small - Rocky package', 'For the inner rockstar', '/img/subscriptions/baby_rocky_1.jpg','/img/subscriptions/baby_complete_2.jpg','/img/subscriptions/baby_complete_3.jpg','/img/subscriptions/baby_complete_4.jpg', 'BABY', 'standard', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The complete package', 'Everything that your child will need', '/img/subscriptions/baby_complete_4.jpg','/img/subscriptions/baby_complete_2.jpg','/img/subscriptions/baby_complete_3.jpg','/img/subscriptions/baby_complete_1.jpg', 'BABY', 'standard', 300);

INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small package', 'Only the most necessary with a mix of colours', '/img/subscriptions/standard_kids02.jpg', '/img/subscriptions/standard_kids01.jpg', '/img/subscriptions/standard_kids03.jpg', '/img/subscriptions/standard_kids04.jpg', 'KIDS', 'standard', 200);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small - Rocky package', 'For the inner rockstar', '/img/subscriptions/rocky_kids02.jpg', '/img/subscriptions/rocky_kids01.jpg', '/img/subscriptions/rocky_kids03.jpg', '/img/subscriptions/rocky_kids04.jpg', 'KIDS', 'Rocky', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The small - Conscious package', 'Clothes from our conscious collections', '/img/subscriptions/conscious_kids02.jpg', '/img/subscriptions/conscious_kids03.jpg', '/img/subscriptions/conscious_kids04.jpg', '/img/subscriptions/conscious_kids01.jpg', 'KIDS', 'Conscious', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete package', 'Only the most necessary with a mix of colours', '/img/subscriptions/standard_kids03.jpg', '/img/subscriptions/standard_kids01.jpg', '/img/subscriptions/standard_kids02.jpg', '/img/subscriptions/standard_kids04.jpg', 'KIDS', 'standard', 200);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete - Rocky package', 'For the inner rockstar', '/img/subscriptions/rocky_kids03.jpg', '/img/subscriptions/rocky_kids01.jpg', '/img/subscriptions/rocky_kids02.jpg', '/img/subscriptions/rocky_kids04.jpg', 'KIDS', 'Rocky', 300);
INSERT INTO Subscription (Name, Description, Img1, Img2, Img3, Img4, Age_Group, Theme, Price) VALUES ('The Complete - Conscious package', 'Clothes from our conscious collections', '/img/subscriptions/conscious_kids03.jpg', '/img/subscriptions/conscious_kids02.jpg', '/img/subscriptions/conscious_kids04.jpg', '/img/subscriptions/conscious_kids01.jpg', 'KIDS', 'Conscious', 300);


INSERT INTO Customer (First_Name, Last_Name, Email, Street_Address, Postal_Code, City, Country) VALUES ('Pippi', 'Långstrump', 'pippi@langstrump.com', 'Villavillekullavägen 2', '11111', 'LindgrenCity', 'Sweden');
INSERT INTO Customer (First_Name, Last_Name, Email, Street_Address, Postal_Code, City, Country) VALUES ('Anton', 'Svensson', 'anton@svensson.se', 'Katthult', '577 94', ' Lönneberga', 'Sweden');
INSERT INTO Customer (First_Name, Last_Name, Email, Street_Address, Postal_Code, City, Country) VALUES ('Test', 'User', 'user', 'Test street 1', '12345', 'Test City', 'Sweden');

INSERT INTO Child (Name, Birthdate, Wears_Dress, Favorite_Color, ParentID, SubscriptionID) VALUES ('Emil', '2014-12-14', 0, 'Blue', (SELECT id FROM Customer WHERE First_Name='Anton' AND Last_Name='Svensson'), (SELECT id FROM Subscription WHERE Name='Small package'));

INSERT INTO BabyChameleonUser (Username, Password) VALUES ('user', '$2a$11$8It8N/w53Kb9vm.BlsA2i.Rfwit5KsIyJ.YD5I8oHHcdApF1c5EXS');
