CREATE TABLE Customer(
ID VARCHAR AUTO_INCREMENT PRIMARY KEY,
CustomerFirstName VARCHAR(50) NOT NULL,
CustomerLastName VARCHAR(50) NOT NULL,
CustomerEmail VARCHAR(50) NOT NULL,
CustomerStreetAddress VARCHAR(50) NOT NULL,
PostalCode VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL,
CreditCardNumber INT,
CreditCardExpirationDate VARCHAR(50),
CvvCode INT,
IDCounter INT NOT NULL
);
CREATE TABLE Admin(
ID VARCHAR AUTO_INCREMENT PRIMARY KEY,
AdminFirstName VARCHAR(50) NOT NULL,
AdminLastName VARCHAR(50) NOT NULL,
AdminEmail VARCHAR(50) NOT NULL
);

CREATE TABLE Subscription(
ID VARCHAR AUTO_INCREMENT PRIMARY KEY,
Subscription_Name VARCHAR(50) NOT NULL,
Subscription_Description VARCHAR(50) NOT NULL,
ImgID VARCHAR(50) NOT NULL,
Age_Group VARCHAR(50) NOT NULL,
Theme VARCHAR(50) NOT NULL
);

CREATE TABLE BabyChameleonUser(
ID VARCHAR AUTO_INCREMENT PRIMARY KEY,
Password VARCHAR(50) NOT NULL,
CustomerID VARCHAR(50),
AdminID VARCHAR(50)
);

CREATE TABLE Child(
ID VARCHAR AUTO_INCREMENT PRIMARY KEY,
ChildName VARCHAR(50) NOT NULL,
AgeGroup VARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
FavoriteColor VARCHAR(50),
FavoriteGarment VARCHAR(50),
ParentID VARCHAR(50) NOT NULL,
SubscriptionID VARCHAR(50) NOT NULL
);


ALTER TABLE BabyChameleonUser ADD FOREIGN KEY (CustomerID) REFERENCES Customer(ID);
ALTER TABLE BabyChameleonUser ADD FOREIGN KEY (AdminID) REFERENCES Admin(ID);
ALTER TABLE Child ADD FOREIGN KEY (ParentID) REFERENCES Customer(ID);
ALTER TABLE Child ADD FOREIGN KEY (SubscriptionID) REFERENCES Subscription(ID);